name: Auto Label Issues (Test)

on:
  issues:
    opened:

jobs:
  log_event:
    runs-on: ubuntu-latest
    steps:
      - name: Log Issue Info
        run: echo "Issue opened: ${{ github.event.issue.number }} at $(date +%s)"
