name: Auto Label Issues

on:
  issues:
    opened:

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues based on title
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const issueTitle = context.payload.issue.title.toLowerCase();
            const labelsToAdd = [];

            if (issueTitle.includes('bug')) {
              labelsToAdd.push('Type: bug');
            }
            if (issueTitle.includes('feature request') || issueTitle.includes('new feature')) {
              labelsToAdd.push('Type: feature');
            }
            if (issueTitle.includes('enhancement') || issueTitle.includes('improve')) {
              labelsToAdd.push('Type: enhancement');
            }
            if (issueTitle.includes('question') || issueTitle.includes('how to')) {
              labelsToAdd.push('Type: question');
            }
            if (issueTitle.includes('documentation') || issueTitle.includes('docs')) {
              labelsToAdd.push('Type: documentation');
            }
            if (issueTitle.includes('frontend') || issueTitle.includes('ui')) {
              labelsToAdd.push('Component: Frontend');
            }
            if (issueTitle.includes('backend') || issueTitle.includes('api')) {
              labelsToAdd.push('Component: Backend');
            }
            if (issueTitle.includes('documentation') || issueTitle.includes('docs')) {
              labelsToAdd.push('Component: Documentation');
            }

            if (labelsToAdd.length > 0) {
              try {
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: labelsToAdd
                });
                console.log('Added labels:', labelsToAdd);
              } catch (error) {
                console.error('Failed to add labels:', error);
              }
            } else {
              console.log('No matching keywords found in the title.');
            }
