name: "Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  update_hacs_manifest:
    name: "Prepare release asset"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
        
      - name: "Create zip"
        run: |
          cd HaCasa
          zip HaCasa-${{ github.ref }}.zip -r ./

      - name: "Upload zip to release"
        uses: "svenstaro/upload-release-action@v1-release"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: "./HaCasa/HaCasa-${{ github.ref }}.zip"
          asset_name: "HaCasa-${{ github.ref }}.zip"
          tag: "${{ github.ref }}"
          overwrite: true
