name: Upload HaCasa ZIP to Release

on:
  release:
    types:
      - created

permissions:
  contents: write  # Required to upload assets to a release

jobs:
  upload-zip:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create ZIP file of the HaCasa folder
      - name: Create ZIP file
        run: zip -r HaCasa.zip HaCasa

      # Upload the ZIP file to the release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./HaCasa.zip
          asset_name: HaCasa.zip
          asset_content_type: application/zip
