name: Create Release Zip

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0

permissions: 
  contents: write # Grant write permissions to GITHUB_TOKEN

jobs:
  create-release-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # Checkout the tagged commit

      - name: Create Release Directory
        run: mkdir release_build

      - name: Copy Relevant Folders
        run: |
          cp -r dashboard release_build/
          cp -r custom_icons release_build/
          cp -r www release_build/
          cp -r themes release_build/

      - name: Package Release Artifact
        run: |
          cd release_build
          zip -r HaCasa-${{ github.ref_name }}.zip *

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: HaCasa-${{ github.ref_name }}.zip
          path: release_build/HaCasa-${{ github.ref_name }}.zip
