name: Create Release Zip

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      tag_name:
        description: 'Tag to use for the release'
        required: true
        default: 'v1.0.0'

permissions: 
  contents: write # Required for creating releases

jobs:
  create-release-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name || github.ref_name }} # Use the provided tag or current ref

      - name: Package Release Artifact
        run: |
          mkdir -p artifacts
          cd HaCasa
          zip -r ../artifacts/HaCasa-${{ github.event.inputs.tag_name || github.ref_name }}.zip *

      - name: Get Release by Tag
        id: get_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/releases/tags/${{ github.event.inputs.tag_name || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/HaCasa-${{ github.event.inputs.tag_name || github.ref_name }}.zip
          asset_name: HaCasa-${{ github.event.inputs.tag_name || github.ref_name }}.zip
          asset_content_type: application/zip
